# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MotelPos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MotelPos
  #pod 'SPIClient-iOS', '~> 2.4.0'
  pod 'SPIClient-iOS', :git => 'https://github.com/AssemblyPayments/spi-client-ios', :branch => 'feature/payattable-preauth-trans'

  target 'MotelPosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MotelPosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
