# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RamenPos' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for RamenPos
    pod 'SPIClient-iOS', '~> 2.9.1'
    # pod 'SPIClient-iOS', :git => 'https://github.com/mx51/spi-client-ios.git', :branch => 'feature/2.9.1'

    
    target 'RamenPosTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'RamenPosUITests' do
        inherit! :search_paths
        # Pods for testing
    end

    post_install do |installer|
            installer.pods_project.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
                config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            end
    end
    
end
