# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RamenPos' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for RamenPos
    pod 'SPIClient-iOS', '~> 2.5.0'

    target 'RamenPosTests' do
        inherit! :search_paths
        # Pods for testing
    end

    target 'RamenPosUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
