# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RamenPos' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for RamenPos
    # pod 'SPIClient-iOS', '~> 2.6.6'
    pod 'SPIClient-iOS', :git => 'https://github.com/mx51/spi-client-ios.git', :branch => 'feature/v2.6.6'
    
    target 'RamenPosTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'RamenPosUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
