# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TablePos' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for TablePos
    pod 'SPIClient-iOS', :git => 'https://github.com/mx51/spi-client-ios.git', :branch => 'patch/2.6.7'

    target 'TablePosTests' do
        inherit! :search_paths
        # Pods for testing
    end

    target 'TablePosUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
