# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TablePos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TablePos
  #pod 'SPIClient-iOS', '~> 2.3.0'
  #pod 'SPIClient-iOS', :path => '~/Documents/GitHub/spi-client-ios/feature-payattable-preauth-trans'
  pod 'SPIClient-iOS', :git => 'https://github.com/AssemblyPayments/spi-client-ios', :branch => 'feature/payattable-preauth-trans'

  target 'TablePosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TablePosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
