# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TablePos' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for TablePos
    pod 'SPIClient-iOS', '~> 2.4.5'
    
    target 'TablePosTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'TablePosUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
