# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'KebabPos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KebabPos
  pod 'SPIClient-iOS',  :git => 'https://github.com/AmirKamali/spi-client-ios.git', :branch => 'master'  

  target 'KebabPosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KebabPosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
